# Generated by Django 4.0.1 on 2022-02-01 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utilisateurs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repetiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite', models.CharField(choices=[('monsieur', 'monsieur'), ('mademoiselle', 'mademoiselle'), ('madame', 'madame')], default='Monsieur', max_length=200, null=True)),
                ('langue', models.CharField(choices=[('fançais', 'fançais'), ('anglais', 'anglais'), ('bilingue', 'bilingue')], default='fançais', max_length=200, null=True)),
                ('age', models.IntegerField(null=True)),
                ('telephone', models.CharField(max_length=200, null=True)),
                ('photoProfil', models.ImageField(blank=True, upload_to=utilisateurs.models.renommer_image)),
                ('niveauEtude', models.CharField(max_length=200, null=True)),
                ('ville', models.CharField(max_length=200, null=True)),
                ('quartier', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite', models.CharField(choices=[('monsieur', 'monsieur'), ('mademoiselle', 'mademoiselle'), ('madame', 'madame')], default='Monsieur', max_length=200, null=True)),
                ('langue', models.CharField(choices=[('fançais', 'fançais'), ('anglais', 'anglais'), ('bilingue', 'bilingue')], default='fançais', max_length=200, null=True)),
                ('age', models.IntegerField(null=True)),
                ('telephone', models.CharField(max_length=200, null=True)),
                ('photoProfil', models.ImageField(blank=True, upload_to=utilisateurs.models.renommer_image)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
