# Generated by Django 4.0.1 on 2022-04-11 13:56

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='classe',
            field=models.CharField(choices=[('Ecole primaire', 'Ecole primaire'), ('6e', '6e'), ('5e', '5e'), ('4e', '4e'), ('3e', '3e'), ('Seconde', 'Seconde'), ('Premiere', 'Premiere'), ('Terminale', 'Terminale'), ('Licence 1', 'Licence 1'), ('Licence 2', 'Licence 2'), ('Licence 3', 'Licence 3')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coursens',
            name='classes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Ecole primaire', 'Ecole primaire'), ('6e', '6e'), ('5e', '5e'), ('4e', '4e'), ('3e', '3e'), ('Seconde', 'Seconde'), ('Premiere', 'Premiere'), ('Terminale', 'Terminale'), ('Licence 1', 'Licence 1'), ('Licence 2', 'Licence 2'), ('Licence 3', 'Licence 3')], max_length=83),
        ),
    ]
