# Generated by Django 4.0.1 on 2022-02-02 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='age',
        ),
        migrations.RemoveField(
            model_name='client',
            name='civilite',
        ),
        migrations.RemoveField(
            model_name='client',
            name='langue',
        ),
        migrations.RemoveField(
            model_name='client',
            name='telephone',
        ),
    ]
