# Generated by Django 4.0.1 on 2022-02-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_repetiteur_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repetiteur',
            name='civilite',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mme', 'Mme')], default='Mr', max_length=200, null=True),
        ),
    ]
