# Generated by Django 4.0.1 on 2022-04-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_alter_client_classe_alter_coursens_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='repetiteur',
            name='nom_image',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
