# Generated by Django 4.0.1 on 2022-02-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_remove_client_age_remove_client_civilite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='quartier',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='ville',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
