# Generated by Django 4.0.1 on 2022-04-24 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_repetiteur_nom_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repetiteur',
            name='nom_image',
        ),
    ]
