# Generated by Django 4.0.1 on 2022-02-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_client_quartier_client_ville'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repetiteur',
            old_name='telephone',
            new_name='telephone1',
        ),
        migrations.AddField(
            model_name='repetiteur',
            name='telephone2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
