# Generated by Django 4.0.1 on 2022-05-06 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utilisateurs', '0005_personne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='langue',
            field=models.CharField(choices=[('français', 'français'), ('anglais', 'anglais'), ('français et anglais', 'français et anglais'), ('autre', 'autre')], default='fançais', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='repetiteur',
            name='langue',
            field=models.CharField(choices=[('français', 'français'), ('anglais', 'anglais'), ('français et anglais', 'français et anglais'), ('autre', 'autre')], default='fançais', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='repetiteur',
            name='photoProfil',
            field=models.ImageField(blank=True, default='profile.jpg', upload_to='photo_profile'),
        ),
        migrations.AlterField(
            model_name='repetiteur',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Repetiteur', to=settings.AUTH_USER_MODEL),
        ),
    ]
