# Generated by Django 4.0.1 on 2022-05-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0008_alter_repetiteur_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repetiteur',
            name='photoProfil',
            field=models.ImageField(blank=True, default='default_img.jpg', null=True, upload_to='image/photo_profile'),
        ),
    ]
