# Generated by Django 4.0.1 on 2022-05-15 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utilisateurs', '0009_alter_repetiteur_photoprofil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classe',
        ),
        migrations.DeleteModel(
            name='CoursEns',
        ),
        migrations.DeleteModel(
            name='Personne',
        ),
        migrations.AlterField(
            model_name='repetiteur',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rep', to=settings.AUTH_USER_MODEL),
        ),
    ]
