# Generated by Django 4.0.1 on 2022-04-11 11:43

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', multiselectfield.db.fields.MultiSelectField(choices=[('Ecole primaire', 'Ecole primaire'), ('6e', '6e'), ('5e', '5e'), ('4e', '4e'), ('3e', '3e'), ('Seconde', 'Seconde'), ('Premiere', 'Premiere'), ('Terminale', 'Terminale'), ('Licence 1', 'Licence 1'), ('Licence 2', 'Licence 2'), ('Licence 3', 'Licence 3')], max_length=83)),
                ('matiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cours.matiere')),
                ('repetiteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.repetiteur')),
            ],
        ),
    ]
