# Generated by Django 4.0.1 on 2022-04-24 10:28

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_type_lieu_cours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_lieu_cours',
            name='lieux',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Chez le prof', 'Chez le prof'), ("Chez l'apprenant", "Chez l'apprenant"), ('En ligne', 'En ligne'), ('Autre lieu', 'Autre lieu')], max_length=49),
        ),
    ]
