# Generated by Django 4.1.3 on 2022-12-16 20:48

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0003_alter_type_lieu_cours_lieux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='classes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Ecole primaire', 'Ecole primaire'), ('6e', '6e'), ('5e', '5e'), ('4e', '4e'), ('3e', '3e'), ('Seconde', 'Seconde'), ('Premiere', 'Premiere'), ('Terminale', 'Terminale'), ('Licence 1', 'Licence 1'), ('Licence 2', 'Licence 2'), ('Licence 3', 'Licence 3')], max_length=100),
        ),
        migrations.AlterField(
            model_name='type_lieu_cours',
            name='lieux',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Chez le prof', 'Chez le prof'), ("Chez l'apprenant", "Chez l'apprenant"), ('En ligne', 'En ligne'), ('Autre lieu', 'Autre lieu')], max_length=100),
        ),
        migrations.AlterField(
            model_name='type_lieu_cours',
            name='types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Individuel', 'Individuel'), ('En groupe', 'En groupe')], max_length=100),
        ),
    ]
